version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "33006:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
  web:
    build: .
    command: bundle exec rails s -p 3001 -b "0.0.0.0"
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - MYSQL_HOST=${DATABASE_HOST}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - .:/video_sharing_web
      - bundle:/bundle
    ports:
      - "3001:3001"
    links:
      - db
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db_data:
    driver: local
  bundle:
    driver: local