default: &default
  host: <%= ENV['REDIS_HOST'] || '127.0.0.1' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  db: 1
development:
  url: <%= ENV.fetch('REDIS_URL', '') %>

test:
  <<: *default

production:
  url: <%= ENV.fetch('REDIS_TLS_URL', '') %>
